{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcp-otel-proxy.serviceAccountName" . }}
  labels:
    {{- include "mcp-otel-proxy.labels" . | nindent 4 }}
{{- end }}
